### ISSUE TITLE
Generic types not displaying nicely

### ISSUE THREAD

**Issue by ovatsus** [tpetricek/FSharp.Formatting#138]
http://fsharp.github.io/FSharp.Data/reference/fsharp-data-runtime-nameutils.html

![image](https://f.cloud.github.com/assets/738761/2245525/dc29d1c6-9d52-11e3-979f-d74e6d43e9ea.png)

This is what VS shows:
![image](https://f.cloud.github.com/assets/738761/2245553/96ed3b56-9d53-11e3-8d59-4931ee633559.png)

**Comment by ovatsus** [comment]
Still repros on latest version

**Comment by tpetricek** [comment]
Closing this as a duplicate of a more recent #269.
