### ISSUE TITLE
Support Docco style literate code

### ISSUE THREAD

**Issue by 7sharp9** [tpetricek/FSharp.Formatting#17]
It would be great if you could generate Docco style literate formatting of code.   I know you can already use the fsx generator on fs files but it would be great to have this option.  [marginalia][1] is a clojure example which also supports mathjax which would be another great feature.  

[1]:http://fogus.github.io/marginalia/

**Comment by dsyme** [comment]
Can we close old feature suggestions like this please?

**Comment by tpetricek** [comment]
I'm generally happy to keep feature suggestions open, but this one needs to be more clear before we can leave it as up-for-grabs, so closing for now.
