### ISSUE TITLE
First line of snippet not rendered

### ISSUE THREAD

**Issue by forki** [tpetricek/FSharp.Formatting#176]
In https://github.com/fsharp/FAKE/pull/494 I got:

    ["Something.fs"]
    |> Fsc (fun p ->
              { p with Output = "Something.dll"
                       FscTarget = Library
                       OtherParams =
                          [ "--nooptimizationdata"
                            "--checked+" ] })

but it renders as 

![image](https://cloud.githubusercontent.com/assets/57396/3486121/6a934298-041f-11e4-9bde-05b7fd36e661.png)

I assume it tries to detect the script language and therefor omits ["Something.fs"].

**Comment by matthid** [comment]
I don't think we can fix this completely. 
`[omit]` can be valid F# code or a command. Rather than trying to do some magic and break people after adding additional commands we should recommend using three backticks (```) in such a case.

    ```fsharp
    [omit]
    |> Fsc (fun p ->
          { p with Output = "Something.dll"
                   FscTarget = Library
                   OtherParams =
                      [ "--nooptimizationdata"
                        "--checked+" ] })
    ```
We should therefore close this. Just my 2 cents.

**Comment by tpetricek** [comment]
I agree. If I'm not mistaken we even already handle commands with this less ambiguous notation, i.e.

    ````fsharp, module=Foo
    let a = 10
    ````
