### ISSUE TITLE
Github Flavored Markdown

### ISSUE THREAD

**Issue by rogeralsing** [tpetricek/FSharp.Formatting#181]
There are a few enhancements I'd like to see:

Page links in the form of  `[[page name]]` does currently not work

Images in the form of `[[/images/foo.png]]` does currently not work

This form of sourcecode does not seem to work either (?)
````
'''csharp   
public void Foo()  //not indented
{
}
'''
````
where `'` should be backtick, dont know how to escape here..

**Comment by tpetricek** [comment]
Nice, this now works!
