### ISSUE TITLE
Can't generate docs on Linux or OSX

### ISSUE THREAD

**Issue by icorderi** [tpetricek/FSharp.Formatting#188]
This is a continuation of [Issue #65](https://github.com/fsprojects/ProjectScaffold/issues/65) from the [scaffolding](https://github.com/fsprojects/ProjectScaffold) project.

@tpetricek suggested to bring the issue over here.

**Comment by haf** [comment]
@matthid also relevant: https://github.com/SuaveIO/suave/issues/141

**Comment by matthid** [comment]
@haf I think the main problem with RazorEngine is lacking documentation not missing features (I tried to improve that a bit in the mean time).

**Comment by tpetricek** [comment]
Thanks to all the recent amazing work by @matthid, F# Formatting can certainly be used on Mono now. There are still a few tricks, but the latest ProjectScaffold does work fine - so I'm finally closing this. Thanks @matthid!

**Comment by haf** [comment]
Well done!

**Comment by icorderi** [comment]
Yay! Great work @matthid!
