### ISSUE TITLE
``FSharp.Literate.Tests.Simple.Can split formatted document and formatted tool tips`` fails

### ISSUE THREAD

**Issue by matthid** [tpetricek/FSharp.Formatting#210]
When I do ``build`` (clean master branch) I get:

	***** FSharp.Literate.Tests.Simple.Parsing simple script and markdown produces the same result

	Tests run: 17, Errors: 0, Failures: 1, Inconclusive: 0, Time: 16,9187426871096 seconds
	  Not run: 5, Invalid: 0, Ignored: 5, Skipped: 0

	Errors and Failures:
	1) Test Failure : FSharp.Literate.Tests.Simple.Can split formatted document and formatted tool tips
		 Expected: String containing "test : int"
	  But was:  <string.Empty>

	at FSharp.Literate.Tests.Simple.Can split formatted document and formatted tool tips() in C:\Projects\FSharp.Formatting\tests\FSharp.Literate.Tests\Tests.fs:line 262

	Tests Not Run:
	1) Ignored : FSharp.Literate.Tests.Eval.All embedded code snippets should be wrapped in a table
	2) Ignored : FSharp.Literate.Tests.Eval.Can disable evaluation on an entire script file
	3) Ignored : FSharp.Literate.Tests.Eval.Can evaluate hidden code snippets
	4) Ignored : FSharp.Literate.Tests.Eval.Can parse and format literate F# script with custom evaluator
	5) Ignored : FSharp.Literate.Tests.Eval.Can parse and format literate F# script with evaluation

	Running build failed.
	Error:
	System.Exception: NUnit test failed (1).
	   at Fake.NUnitSequential.NUnit(FSharpFunc`2 setParams, IEnumerable`1 assemblies) in D:\code\fake\src\app\FakeLib\UnitTest\NUnit\Sequential.fs:line 45
	   at FSI_0001.Build.clo@117-11.Invoke(Unit unitVar0) in C:\Projects\FSharp.Formatting\build.fsx:line 118
	   at Fake.TargetHelper.runTarget@314(String targetName) in D:\code\fake\src\app\FakeLib\TargetHelper.fs:line 325

This is a Windows machine with VS2013 if that helps anything

**Comment by tpetricek** [comment]
I think this should not be happening anymore (the issue was related to FSharp.Compiler.Service.interactive.dll, which is fixed by recent commits, I hope!)

**Comment by matthid** [comment]
For future reference: Just saw this again with a different reason: FSharp.Core was copied in the test output directory -> optdata and sigdata missing -> FSharp.Compiler.Service is failing silently.
