### ISSUE TITLE
Apostrophes in indented code blocks are double-encoded and then highlighted

### ISSUE THREAD

**Issue by palpha** [tpetricek/FSharp.Formatting#213]
Here's a quick repro of the problem. Ran into this while trying to use FsReveal to create a presentation in which I show examples in both F#, C# and JS. I can work around it for many things, but chars in C# are hard to do without apostrophes :).

    #I "../packages/FSharp.Formatting.2.4.30/lib/net40"
    #I "../packages/RazorEngine.3.3.0/lib/net40"
    #I "../packages/FSharp.Compiler.Service.0.0.62/lib/net40"
    #r "FSharp.Markdown.dll"
    #r "FSharp.Literate.dll"
    #r "FSharp.CodeFormat.dll"

    open FSharp.Literate

    Literate.ParseScriptString """
    (**
    Look ma', I'm good.

        [lang=js]
        var but = 'I\'m not so good...';
    *)
    """
    |> Literate.WriteHtml

    (*
    <p>Look ma', I'm good.</p>

    <table class="pre"><tr><td><pre lang="js"><span class="k">var</span> but <span class="o">=</span> <span class="o">&amp;</span>#39;I\<span class="o">&amp;</span>#39;m not so good...<span class="o">&amp;</span>#39;;</pre></td></tr></table>
    *)

**Comment by Vidarls** [comment]
Seems to be the same issue as #249

**Comment by forki** [comment]
this also creeps into FsReveal and makes F# presentations which show generics parameters a mess.
 @tpetricek could you please take a look.

**Comment by forki** [comment]
did you try to save your index.md in UTF-8?
