### ISSUE TITLE
FCS dependency is not version restricted and latest FCS breaks stuff

### ISSUE THREAD

**Issue by Vidarls** [tpetricek/FSharp.Formatting#219]
Ref fsprojects/ProjectScaffold#104 

Not sure what is the best approach here, main problem is that the latest FCS seems to be using stuff that is not yet available as a general download (i.e. the downloads of fsharp.org) and as such breaks Fsharp.formatting cause no upper limit is put on the FCS dependency.

**Comment by forki** [comment]
fixed - we are compatible again
