### ISSUE TITLE
Line numbers in C#

### ISSUE THREAD

**Issue by luajalla** [tpetricek/FSharp.Formatting#227]
Currently it's possible to add/remove line numbers from the F# snippets only, it would be nice to have a support for other languages as well. 
``SourceFormat`` (and ``CSharpFormat`` in particular) have an option to generate the line numbers, but it's always set to default. The only issue with it is that html structure is different from F# one: you can't easily copy the code without numbers.

**Comment by tpetricek** [comment]
This is now implemented :-)
