### ISSUE TITLE
"You must add a reference to assembly 'RazorEngine'" error when following "Typical literate setup" docs

### ISSUE THREAD

**Issue by jamesjrg** [tpetricek/FSharp.Formatting#232]
I tried following the documentation at:

http://tpetricek.github.io/FSharp.Formatting/literate.html

and got the error: "error FS0074: The type referenced through 'RazorEngine.Templating.ITemplateResolver' is defined in an assembly that is not referenced. You must add a reference
to assembly 'RazorEngine'."

Rightly or wrongly I fixed this problem by adding the following line to the top of my build.fsx script:

#I "packages/RazorEngine/lib/net40"

I also had to change the path to the formatting library, as it doesn't seem to include the version number in the package directory:

#I "packages/FSharp.Formatting/lib/net40"

**Comment by tpetricek** [comment]
Should be fixed by https://github.com/tpetricek/FSharp.Formatting/commit/e6c755fe79ced0b1d776004a6d33484288ebb7dd and https://github.com/tpetricek/FSharp.Formatting/commit/5283f91951f0c38d88c1e1816a6e657b6439338c. Thanks for reporting this!
