### ISSUE TITLE
Handling of non-ascii characters

### ISSUE THREAD

**Issue by Vidarls** [tpetricek/FSharp.Formatting#249]
Using html entities within code blocks to represent non-ascii characters seems to not be working. (Assuming that the reason is that html entities within `<pre></pre> ` blocks are not expanded, but rendered as literates.)

Is there really any need for html entities when outpout is utf-8?

**Comment by tpetricek** [comment]
I suspect that we're not doing anything clever to handle HTML entities - but I'm not quite sure what issue are you specifically describing here.

Can you post an example of Markdown input together with what F# Formatting currently generates and what you would expect it to generate? (In general, I'd like to follow CommonMark specification, so you can also check what [CommonMark says about entities](http://spec.commonmark.org/0.15/#entities))

**Comment by Vidarls** [comment]
Some more investigation reveals that this seems to be an issue with SQL code highlighter:

This markdown:
```
Some norwegian letters: ÆØÅ

A code block with Some Norwegian letters:

    [lang=sql]
    Æøå
```

Generates this html

```html
<p>Some norwegian letters: ÆØÅ</p>

<p>A code block with Some Norwegian letters:</p>

<table class="pre"><tr><td><pre lang="sql">&amp;#198;&amp;#248;&amp;#229;</pre></td></tr></table>
```

**Comment by Vidarls** [comment]
A more elaborate test:

```md
A SQL code block with Some Norwegian letters:

    [lang=sql]
    Æøå

A non language specific SQL code block:

    Norwegian chars for the win: ÆØÅæøå

A c# code block

    [lang=c#]
     var æøå = "ÆØÅ"
```


Generated HTML:
```html
<p>Some norwegian letters: ÆØÅ</p>

<p>A SQL code block with Some Norwegian letters:</p>

<table class="pre"><tr><td><pre lang="sql">&amp;#198;&amp;#248;&amp;#229;</pre></td></tr></table>

<p>A non language specific SQL code block:</p>

<table class="pre"><tr><td class="lines"><pre class="fssnip">
<span class="l">1: </span>
</pre>
</td>
<td class="snippet"><pre class="fssnip">
<span class="i">Norwegian</span> <span class="i">chars</span> <span class="k">for</span> <span class="i">the</span> <span class="i">win</span><span class="o">:</span> <span class="i">&#198;&#216;&#197;&#230;&#248;&#229;</span></pre>
</td>
</tr>
</table>

<p>A c# code block</p>

<table class="pre"><tr><td><pre lang="c#">var &#230;&#248;&#229; = &quot;&#198;&#216;&#197;&quot;</pre></td></tr></table>
```

Some times the entities are displaying as expected, other times, the entities are displayed unexpanded. Don't know enouth abt html and entities to have an opinion as to why

**Comment by Vidarls** [comment]
It looks like the SQL processor, expands the ampersand int the entitiy aswell, this is not done in the other two code snippets examples.

IE:

```
Æ => &#198; => &amp;#198;
```
