### ISSUE TITLE
Syntax coloring for Paket files [WAS: Special case for URLs]

### ISSUE THREAD

**Issue by forki** [tpetricek/FSharp.Formatting#262]
I know we misuse the F# formatter for Paket docs:

![image](https://cloud.githubusercontent.com/assets/57396/6096124/61000186-af81-11e4-806d-622c1aacf97d.png)

but the latest version of FSharp.Formatting colors comments like above. Which is correct from a F# standpoint.

Anyways, it would be cool if we could somehow special case the URLs.

/cc @tpetricek @vasily-kirichenko @agross

**Comment by tpetricek** [comment]
You can use a different formatting for non-F# code snippets. This is using a low-tech C#-based code formatter, which is more basic, but does the trick. You can do that by putting `[lang=...]` on the line before:

    [lang=csharp]
    class FancyDemoFactoryBuilder { /* .... */ }

The formatters are [implemented here](https://github.com/tpetricek/FSharp.Formatting/tree/master/src/CSharpFormat) and the (undocumented) language tags [are here](https://github.com/tpetricek/FSharp.Formatting/blob/master/src/CSharpFormat/SyntaxHighlighter.cs#L52). 

It might be doable to put together a really basic one for Paket file format?

**Comment by matthid** [comment]
https://github.com/tpetricek/FSharp.Formatting/pull/379
