### ISSUE TITLE
Strange rendering of type parameters

### ISSUE THREAD

**Issue by forki** [tpetricek/FSharp.Formatting#269]
![image](https://cloud.githubusercontent.com/assets/57396/6410048/61247e64-be6b-11e4-9b2e-817c75079af1.png)

Any ideas where I did something wrong?

**Comment by tpetricek** [comment]
Eh, this happens when the type parameter name is automatically generated. I guess the recommendation is to add an explicit type annotation:

    let foo f a = f a // Generates ugly names for type parameters
    let bar f (a:'TInput) : 'TResult = f a // All are explicitly named

For some reason, the F# Compiler Service returns those ugly names instead of replacing them with acceptable `'a, 'b, 'c`.. as the IDE does. It would be nice to rename those in F# Formatting too, though...

**Comment by forki** [comment]
So it's actually something that should be addressed in FCS?

**Comment by tpetricek** [comment]
I would not call this FCS *bug* - if the intended behavior is to return ugly names, then that's fine :-). But FCS would be a logical place to improve this - and I don't think anybody would want to see the ugly internal IDs!

**Comment by matthid** [comment]
Looks like a duplicate of https://github.com/tpetricek/FSharp.Formatting/issues/138

**Comment by tpetricek** [comment]
I marked this as `up-for-grabs`. I suppose that we could probably implement automatic renaming of generated type parameters ourselves in F# Formatting as a workaround (although handling this in F# Compiler Service would be nicer).

**Comment by matthid** [comment]
I just found https://github.com/tpetricek/FSharp.Formatting/issues/39, which seems to be related as well (but not exactly the same). Probably something to think about when fixing either of those issues.

**Comment by 7sharp9** [comment]
I fixed some of these in FCS as it was bug there.

**Comment by ovatsus** [comment]
Seems this is now fixed with latest version of both FCS and FF, so the issue can probably be closed

**Comment by tpetricek** [comment]
Excellent news :)
