### ISSUE TITLE
LaTeX formatting of F# code snippets is broken

### ISSUE THREAD

**Issue by tpetricek** [tpetricek/FSharp.Formatting#278]
The PR to use F# PowerTools formatting added HTML formatting for the additional types of tokens, but **not** for LaTeX. I added [workaround for this here](https://github.com/tpetricek/FSharp.Formatting/commit/2a1af08710228f7cb879c00a2b55af93586a4bd6), but it would be great to cover the additional cases properly (we do not need to make the LaTeX template fancier, but we should map the new tokens to the closest existing kind of token).

@vasily-kirichenko Could you have a look at this?

**Comment by dungpa** [comment]
Hey,

Can I have a look at this?

I wanted to update https://github.com/dungpa/fsharp-cheatsheet to use semantic highlighting for LaTeX for some time.
