### ISSUE TITLE
Stopped due to error

### ISSUE THREAD

**Issue by halcwb** [tpetricek/FSharp.Formatting#291]
While trying to generate api references, I get a 'Stopped due to error'? There is no other clue to what or where the error occurs.

**Comment by matthid** [comment]
It's quite difficult to look into this without further information.
Can you provide a repro? Does that happen always? On all your projects? mono or .net?
Possibly a stackoverflow and related to https://github.com/fsprojects/FSharpx.Reflection/issues/1?

**Comment by tpetricek** [comment]
This is just psychic debugging... but the error often happens when the F# Compiler Service cannot find some dependencies. Can you check the `libDirs` parameter (and make sure that it points to locations where various dependencies might be?)

**Comment by halcwb** [comment]
Sorry for the lack of info. I think it was because of a missing doc xml file. I reported this because it didn't give a clue what was going on. It also could be due to a missing dependency. If there are no obvious fixable clues, I guess closing this is good enough. I will report back when this happens again.
