### ISSUE TITLE
Handle <parameter> etc for XML comments

### ISSUE THREAD

**Issue by zealisland** [tpetricek/FSharp.Formatting#295]
In http://tpetricek.github.io/FSharp.Formatting/metadata.html, it mentions that 

_Note that currently our code is not handling \<parameter\> and ` tags, this is not so much of a problem given that given that FSharp.Formatting infers the signature via reflection._

Just want to check whether this is on the roadmap? If so, when will \<parameter\> etc be supported?

Thanks!

**Comment by tpetricek** [comment]
We'd be happy to add support for this. 

If you're interested in contributing, this is something that can be handled in the `readXmlComment` function [here in the source code](https://github.com/tpetricek/FSharp.Formatting/blob/master/src/FSharp.MetadataFormat/Main.fs#L503). I think that all that needs to be done is to change it to recognisze the `<parameter>` tag and turn it into `<ul>` HTML element with `<li>` elements for all parameters (and append this to the generated string). So it should be a nice issue for a new contributor :-).

(There is also a project `csharpSupport` in `tests` folder, so this is a place where you can add a sample documented method, which can then be processed and checked by the tests.)

**Comment by matthid** [comment]
I think this has been merged an released with #331.
