### ISSUE TITLE
System.TypeLoadException : Method 'get_LineCount' in type 'lexer@289' from assembly 'FSharp.CodeFormat

### ISSUE THREAD

**Issue by ovatsus** [tpetricek/FSharp.Formatting#301]
I did a paket update:

![image](https://cloud.githubusercontent.com/assets/738761/7219288/68b82688-e690-11e4-92a6-bbcb30612d91.png)

And now I get this when running the documentation tests:

![image](https://cloud.githubusercontent.com/assets/738761/7219285/56af08b2-e690-11e4-8c9a-ceee5854d217.png)

Is there something I need to fix?

**Comment by forki** [comment]
I saw this before and I thought @tomaspetricek said that we we need to pin a dependency (IIRC the powetools). But I would like to see the pin happen directly in FSF so that it solves it for everyone.

**Comment by matthid** [comment]
Lock FSharpVSPowerTool to 1.7.0, see #294  #277.
I think this is already fixed in master, there is just no NuGet release with the fix (jet).

**Comment by forki** [comment]
Ok what is missing? Why can't we just release this fixed version on nuget?

**Comment by ovatsus** [comment]
Humm, I'm not even referencing FSharpVSPowerTool directly, should I?

**Comment by matthid** [comment]
@ovatsus Either that or stay on an older FSharp.Formatting version

@forki: We need to ask @tpetricek, but I would assume he wants to look over the open PRs or do some further testing or just has not found the time to do it :). 

It's a bit sad that the next release will probably break everyone who locked the powertools version again. Does paket throw an error if FSharp.Formatting is locked to 1.8 and the dependencies file is locked to 1.7 or will it simply use 1.7?

**Comment by forki** [comment]
No normally you shouldn't. That's why I'd like to see a new fsf package. But in order to get your current issue fixed: Yes you need to add the powetools to the dependencies file and pin the version. 

Or you revert the update and wait a bit.

**Comment by forki** [comment]
@matthid: it will not throw. It will just not update since it tries to unify all requirements. That means it will install the latest fsf that's compatible to your pinned powertools version. That means it might never update again -  until you remove the pin.

**Comment by ovatsus** [comment]
BTW, that paragraph should be on Paket docs

**Comment by ovatsus** [comment]
(and the output of paket should maybe log when it doesn't get the latest of some package because of a pin of a dependent package)

**Comment by forki** [comment]
Good idea. I created two issues

**Comment by ovatsus** [comment]
Great, thanks!

**Comment by tpetricek** [comment]
Sorry everyone for the delay…

 

@tpetricek not only had to do some testing, but also had to do one talk in Prague, another at F# eXchange, move to Cambridge, do F# trainings & various other stuff. Oh, and he also didn’t have internet at home… 

 

In any case, new version of F# Formatting with all the fixes should now be released!
