### ISSUE TITLE
Diagnosing "No value returned" / "No output"

### ISSUE THREAD

**Issue by slyons** [tpetricek/FSharp.Formatting#312]
I am working with Literate F# / FSLab and through FSI I can see that my code is producing valid Deedle Frames, but when I try to generate the HTML it only generates "No value returned". As a side effect, any "include-value" statements that follow my code also start rendering as "No value returned". 

Is there a way to diagnose why this is happening?

**Comment by tpetricek** [comment]
Can you share (some bits of) the code that you are using? (i.e. how you define values and what special commands with `***` are you using...)?

**Comment by slyons** [comment]
I am loading a collection of .NET objects into a Frame using Frame.ofRecords, then simply trying to output the number of rows as a first test. I'm assuming that there's some object that can't be rendered somehow, but I'm struggling to figure out which one.

**Comment by tpetricek** [comment]
You can either use `(*** define-output: sth ***)` and `(*** include-it: sth ***) which will include the output of whatever value was returned by the snippet - [see this example](https://github.com/fslaborg/FsLab.Templates/blob/journal/Tutorial.fsx#L68), or you can just have snippet that defines values using `let myFrame = ...` and then you can use `(*** include-it: myFrame ***)`.

I think you can get "No value returned" if you mix these commands wrongly... It would be easier to debug if you could share a part of your snippet...

**Comment by slyons** [comment]
(*** define-output:rcount ***)
let jobList = <function that returns seq of jobs>

jobList |> Seq.count
(*** include-output:rcount ***)

Result:
No output / No value returned
No value returned

**Comment by tpetricek** [comment]
Ah... `(*** include-output:rcount ***)` will embed whatever the snippet *printed*, but here, you want to embed whatever was the _result_ of the snippet, which is done with `(*** include-it:rcount ***)`.

I think the commands are not very elegant and we should simplify this, so proposals how this could be done better are welcome :-). Perhaps just automatically embed the "right" thing?

**Comment by slyons** [comment]
Okay so my snippet wasn't 100% clear. I have tried both include-output include-it and both produce the appropriate message equivalent to "No value returned". I tried both options and it resulted in the same thing.

**Comment by tpetricek** [comment]
Can you share a minimal reproducible sample that I could run locally? It is a bit difficult to guess what might be going wrong here...

**Comment by slyons** [comment]
I can't really share much of anything in the way of a snippet, but I have narrowed down the issue. I started with the blank template, with the following snippet:  

    let myThing = 0
    (*** include-value:myThing ***) 

And slowly re-introduced my custom code one step at a time. It would always output 0 until I uncommented one line in particular, which now results in: `No value has been returned`. Is there something in the custom code (which is an external library) that could interfere with how data is captured by FSlab?

**Comment by tpetricek** [comment]
Hmmm, interesting - I suspect this could be some issue related to referencing the library - perhaps - for some reason - the FsLab evaluator is failing to load the library (or one of its dependencies).

Which version of the runner are you using? The most recent one (which automatically updates the journal when you save the file)? If no - can you try updating? I think the most recent one might come with better error reporting!

**Comment by slyons** [comment]
Based on what the template is generating for me, 0.1.3 is the version I'm using. I'm not entirely familiar with paket. It seems to claim some packages I have are out of date but I can't seem to update them if they are. I also don't see automatic journal updates, either.

**Comment by tpetricek** [comment]
I did some breaking changes in the template recently - so updating would not quite work at the moment (sorry about that!) Could you get the latest version, create a new project & copy everything there? 

(With the new version, you will just be able to run `.paket/paket.exe update` and get the latest version, but it required some not-very-nice changes!)

**Comment by slyons** [comment]
I've updated to the new version and I'm still getting the lack of input, although this time the inclusion of the library does not affect output from the rest of the document. So that's an improvement :) I'm still experimenting to see if I can track down why the result is still failing.

**Comment by slyons** [comment]
It seems I was incorrect. I think that my external code is redirecting output somehow and is preventing the FSI evaluator from capturing the output.

**Comment by slyons** [comment]
We can close this issue. It turns out it couldn't load the assembly and the newer version had output saying as much. Thanks for all your help!

**Comment by tpetricek** [comment]
Thanks for taking the time to investigate this. Also, I'm happy to hear that the new version made finding the error easier (or, actually possible :-))!
