### ISSUE TITLE
FSharp.Literate does not escape HTML entities in code blocks with unknown language

### ISSUE THREAD

**Issue by cr7pt0gr4ph7** [tpetricek/FSharp.Formatting#321]
When using e.g. `FSharp.Literate.ProcessDirectory` to generate HTML from Markdown, **code blocks with unknown languages** (e.g. `batchfile`) receive no escaping of special HTML characters (&, <, >).

This issues seems to only affect code blocks with languages that are unknown to `CSharpFormat.SyntaxHighlighter.FormatCode`. Code blocks with known languages and inline code blocks do receive correct escaping.

Contents:
* **Reproduction steps**
* **Details / Root cause**
* **Possible solution**

## Reproduction steps
In practice, that means that:
```
[lang=batchfile]
program --argument <string>
```
results in the following HTML:
```html
<code>program --argument <string></code>
```
instead of:
```html
<code>program --argument &lt;string&gt;
```

## Details / Root cause
When a code snippet is to be formatted, the following steps occur (only relevant parts are included):

1. [`Transformations.replaceSpecialCodes`](https://github.com/tpetricek/FSharp.Formatting/blob/master/src/FSharp.Literate/Transformations.fs#L350) calls [`SyntaxHighlighter.FormatCode`](https://github.com/tpetricek/FSharp.Formatting/blob/master/src/CSharpFormat/SyntaxHighlighter.cs#L47) to turn the raw code into formatted HTML.
2. [`SyntaxHighlighter.FormatCode`](https://github.com/tpetricek/FSharp.Formatting/blob/master/src/CSharpFormat/SyntaxHighlighter.cs#L95) looks up the correct source formatter `sf` for the specified language.
  1. *If the language is known*: `sf.FormatCode(string)` is called. The [default implementation](https://github.com/tpetricek/FSharp.Formatting/blob/master/src/CSharpFormat/SourceFormat.cs#L134) calls the private function [`SourceFormat.FormatCode`](https://github.com/tpetricek/FSharp.Formatting/blob/master/src/CSharpFormat/SourceFormat.cs#L187), which, besides other things,  replaces special HTML characters (&, <, >) with the appropriate HTML entities.
  2. *If the language is not known*: The raw code is returned without changes. **No encoding of special HTML characters is applied.**
3. [`Transformations.replaceSpecialCodes`](https://github.com/tpetricek/FSharp.Formatting/blob/master/src/FSharp.Literate/Transformations.fs#L350) writes the result of `SyntaxHighlighter.FormatCode` into the output (that is, either the HTML output from the formatter, or the unescaped code).

## Possible solution
The solution for this problem is rather simple: Either [`SyntaxHighlighter.FormatCode`](https://github.com/tpetricek/FSharp.Formatting/blob/master/src/CSharpFormat/SyntaxHighlighter.cs#L95) or [`Transformations.replaceSpecialCodes`](https://github.com/tpetricek/FSharp.Formatting/blob/master/src/FSharp.Literate/Transformations.fs#L350) calls [`SyntaxHighlighter.FormatCode`](https://github.com/tpetricek/FSharp.Formatting/blob/master/src/CSharpFormat/SyntaxHighlighter.cs#L47) should apply escaping of special HTML characters even if the language is not known.

In my opinion, the change should be applied to  `SyntaxHighlighter`, because the safe escaping of the output should not depend on whether the language is known or not.

On the other hand, if `CSharpFormat.SyntaxHighlighter` is considered to be a public API, the change might break some clients outside of `FSharp.Formatting` that expect `SyntaxHighlighter.FormatCode` to return the unescaped input if the language is not known (e.g. because they already use a workaround for the issue described here). But it is also likely that other clients produce invalid HTML because they do not employ a workaround.

**Comment by tpetricek** [comment]
Thank you for a detailed analysis. 

If you can send a pull request that fixes this issue, that would be amazing. I agree with your analysis - it sounds like fixing `SyntaxHighlighter.FormatCode` so that it encodes special HTML characters (even when the language is not known) is the best way to get it fixed. I would not worry that anyone calls this API directly, so this should be fine.

(Also, please add a test checking this behavior to make sure we don't break this in the future :-))
