### ISSUE TITLE
Error FS0192 when running generate.fsx

### ISSUE THREAD

**Issue by gsscoder** [tpetricek/FSharp.Formatting#334]
Hi there,
I'm new to this powerful tool, so I'm sorry if I'm missing something obvious.

I'd like to use **FSharp.Formatting** to create a small presentation web site for a new release of an open source project I maintain.

This is the error I get when running `fsi --exec generate.fsx`:
```PowerShell
error FS0192: internal error: convMethodRef: could not bind to method
```

For reference this is the project `docs` folder: https://github.com/gsscoder/commandline/tree/master/docs.

Thanks in advance!

**Comment by tpetricek** [comment]
Can you try referencing the F# Formatting using `#load` with the load script, as [in the ProjectScaffold example](https://github.com/fsprojects/ProjectScaffold/blob/master/docs/tools/generate.template#L31)?

**Comment by gsscoder** [comment]
@tpetricek, thanks for replying. Yes, I've added the `#load` directive to [generate.fsx](https://github.com/gsscoder/commandline/blob/master/docs/tools/generate.fsx#L29), this the new output:
```PowerShell
PS P:\CommandLine\docs\tools> fsi --exec .\generate.fsx
FSharp.Formatting Information: 0 : FSharp.Formatting Logging setup!
Yaaf.FSharp.Scriping Information: 0 : Yaaf.FSharp.Scripting Logging setup!


error FS0192: internal error: convMethodRef: could not bind to method
```
Something changed, in fact now a [log file](https://github.com/gsscoder/commandline/blob/master/docs/tools/FSharp.Formatting.svclog) was also created.

Can I try something else?

**Comment by tpetricek** [comment]
Hmm, what version of F# are you using? I think I've seen this error with some of the earlier builds of F# 3.0 (but it was fixed in later versions).

Could you perhaps try to produce a minimal repro? (Removing references & code that don't matter and producing a ZIP file I could try running on my machine?)

**Comment by gsscoder** [comment]
@tpetricek, maybe you're right about version. I've simply used the `fsi` in my power shell path:
```PowerShell
PS P:\CommandLine\docs\tools> fsi --help
Microsoft (R) F# 2.0 Interactive build 4.0.40219.1
Copyright (c) Microsoft Corporation. All Rights Reserved.

Usage: fsi.exe <options> [script.fsx [<arguments>]]


                - INPUT FILES -
--use:<file>                   Use the given file on startup as initial input
--load:<file>                  #load the given file on startup
--reference:<file>             Reference an assembly (Short form: -r)
```

> Could you perhaps try to produce a minimal repro? (Removing references & code that don't matter and producing a ZIP file I could try running on my machine?)

Can you be more explicit, please... :confused:  I think you're not talking about the script(s), since these are available in my repository [here](https://github.com/gsscoder/commandline/tree/master/docs).
_Please let me understand and I'll send you everything you want or make any test you ask._

(And thanks again for your time).

**Comment by tpetricek** [comment]
I suspect this could be due to the version of F# Interactive. The version I have is:

> Microsoft (R) F# Interactive version 12.0.21005.1  
> Copyright (c) Microsoft Corporation. All Rights Reserved.

If you're using VS 2013, then I think this is [the latest release](http://blogs.msdn.com/b/fsharpteam/archive/2014/08/20/announcing-the-release-of-visual-f-tools-3-1-2.aspx).

**Comment by gsscoder** [comment]
I use VS 2012 Ultimate also if in this dev machine is there a VS 2013 C.E. (with license expired).

Probably this is not the place to ask help with that... (So please be patient if I'm wrong).

I've downloaded `FSharp_Bundle.exe` from CodePlex but installation fails with this [log](https://gist.github.com/gsscoder/3e19687d426045332642).
![failed-fsharp_bundle-inst_sshot](https://cloud.githubusercontent.com/assets/1194228/9042521/909adc2c-3a0f-11e5-99ac-44e430f7230b.png)

Is this a sort of security problem? Some policy that must be "unlocked"?

I'll try to fix the installation problem... But if you've any suggestion, it'll be welcome!

**Comment by tpetricek** [comment]
Hmm, I think you need VS 2013 to install the latest version. I think the Community Edition should be free though! See: https://www.visualstudio.com/en-us/products/visual-studio-community-vs.aspx

**Comment by gsscoder** [comment]
I feel so dumb... I just required a new license and C.E. is now active again! :(

Now it is self-updating. I think it's able to install an updated `Fsi.exe` on its own. Anyway I can try to run `FSharp_Bundle.exe` when update completes.

I've tried to run the setup from Control Panel, but if I try to modify the installation there's no specific option to add F# stuff.

I'll post here my progresses. For the moment, thanks for **useful** info as always! :+1:

**Comment by gsscoder** [comment]
Everything is updated. I've your FSharp Interactive version inside Visual Studio too.
```
Microsoft (R) F# Interactive version 12.0.30815.0
Copyright (c) Microsoft Corporation. All Rights Reserved.

For help type #help;;

> 
```
But the only executable `Fsi.exe` I can find on my machine, when launched from terminal, it seems the old one, with outdated version number.

I guess I've to start ``generate.fsx` using Visual Studio F# Interactive at this point. Am I right?

**Comment by gsscoder** [comment]
Wow! It worked. Thanks for support, @tpetricek.
I think that still some little detail to tune, but it's outside the _scope_ of this issue (I'll open another specific issue eventually).

```fsharp
> #load @"P:\CommandLine\docs\tools\generate.fsx";;
[Loading P:\CommandLine\packages\FSharp.Formatting\FSharp.Formatting.fsx
 Loading P:\CommandLine\docs\tools\generate.fsx]
Binding session to 'P:\CommandLine\packages\FSharp.Formatting\../FSharpVSPowerTools.Core/lib/net45\FSharpVSPowerTools.Core.dll'...
Binding session to 'P:\CommandLine\packages\FSharp.Formatting\../FSharp.Compiler.Service/lib/net45\FSharp.Compiler.Service.dll'...
FSharp.Formatting Information: 0 : FSharp.Formatting Logging setup!
Yaaf.FSharp.Scriping Information: 0 : Yaaf.FSharp.Scripting Logging setup!
Deleting contents of P:\CommandLine\docs\tools\../output
P:\CommandLine\docs\output already exists.
Copying file: P:\CommandLine\docs\output\img\logo-template.pdn
Copying file: P:\CommandLine\docs\output\img\logo.png
Copying styles and scripts: P:\CommandLine\docs\output\content\style.css
Copying styles and scripts: P:\CommandLine\docs\output\content\style.css.bak
Copying styles and scripts: P:\CommandLine\docs\output\content\style_light.css
Copying styles and scripts: P:\CommandLine\docs\output\content\tips.js
Copying styles and scripts: P:\CommandLine\docs\output\content\img\github-blue.png
Copying styles and scripts: P:\CommandLine\docs\output\content\img\github.png
Binding session to 'P:\CommandLine\packages\FSharp.Formatting\lib/net40\FSharp.CodeFormat.dll'...
Generating 'P:\CommandLine\docs\tools\..\content/index.html'
Binding session to 'P:\CommandLine\packages\FSharp.Formatting\lib/net40\FSharp.Literate.dll'...
Binding session to 'P:\CommandLine\packages\FSharp.Formatting\lib/net40\RazorEngine.dll'...
Binding session to 'P:\CommandLine\packages\FSharp.Formatting\lib/net40\RazorEngine.dll'...
Binding session to 'P:\CommandLine\packages\FSharp.Formatting\lib/net40\FSharp.Literate.dll'...
Generating 'P:\CommandLine\docs\tools\..\content/tutorial.html'
Creating P:\CommandLine\docs\output\reference
Yaaf.FSharp.Scriping Warning: 0 : Parsing and checking warnings: 
	**** error: Problem reading assembly '': Exception of type 'Microsoft.FSharp.Compiler.ErrorLogger+InternalError' was thrown.
	**** error: internal error: PrepareToImportReferencedIlDll: cannot reference .NET netmodules directly, reference the containing assembly instead
	**** error: Problem reading assembly '': Error opening binary file 'C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.0\System.EnterpriseServices.Thunk.dll': C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.0\System.EnterpriseServices.Thunk.dll: bad cli header, rva 0
	**** error: Error opening binary file 'C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.0\System.EnterpriseServices.Thunk.dll': C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.0\System.EnterpriseServices.Thunk.dll: bad cli header, rva 0
	**** error: Assembly reference 'P:\CommandLine\bin\net40\CommandLine.dll' was not found or is invalid
FSharp.Formatting Warning: 0 : **** Skipping assembly 'P:\CommandLine\bin\net40\CommandLine.dll' because was not found in resolved assembly list
FSharp.Formatting Information: 0 : Starting razor engine
FSharp.Formatting Information: 0 : Generating: index.html
Binding session to 'P:\CommandLine\packages\FSharp.Formatting\lib/net40\FSharp.MetadataFormat.dll'...
Binding session to 'P:\CommandLine\packages\FSharp.Formatting\lib/net40\FSharp.MetadataFormat.dll'...
FSharp.Formatting Information: 0 : Generating modules...
FSharp.Formatting Information: 0 : Generating types...

namespace FSI_0002.FSharp
  val svclogFile : string
  val logFile : string
  type TraceOptions = System.Diagnostics.TraceOptions
  val allTraceOptions : System.Diagnostics.TraceOptions
  val noTraceOptions : System.Diagnostics.TraceOptions
  val listeners : System.Diagnostics.TraceListener []
  val sources : System.Diagnostics.TraceSource list


namespace FSI_0002
  val referenceBinaries : string list
  val website : string
  val githubLink : string
  val info : (string * string) list
  val root : string
  val bin : string
  val content : string
  val output : string
  val files : string
  val templates : string
  val formatting : string
  val docTemplate : string
  val layoutRoots : string list
  val copyFiles : unit -> unit
  val buildReference : unit -> unit
  val buildDocumentation : unit -> unit

> 
```
