### ISSUE TITLE
Markdown parser doesn't recognize CodeBlock inside QuotedBlock

### ISSUE THREAD

**Issue by ljw1004** [tpetricek/FSharp.Formatting#342]
Look at this piece of markdown, and how it renders, and then how it parses in FSharp.Markdown:

```
> __Annotation__
> This is an annnotation
> ```vb
> Module Module1
> End Module
> ```
> More annotation
```

-----------------------------

> __Annotation__
> This is an annnotation
> ```vb
> Module Module1
> End Module
> ```
> More annotation

-------------------------

But FSharp.Markdown parses the quoted block like this:

*   QuotedBlock
    *   Paragraph
        *   Strong
            * Literal "Annotation"
        *   Literal "This is an annotation”
        *   InlineCode "`vb\nModule Module1\nEnd Module"
    *   Literal "More annotation"

It should parse it as a CodeBlock, but it's actually parsing it as an InlineCode.

**Comment by ljw1004** [comment]
It's even worse that that! If the QuotedBlock contains any InlineCode after the CodeBlock, then it parses wrong -- e.g.

```
> Hello
> ```vb
> Module1
> ```
> That was an `inline` code block
```

Here it renders `That was an` as an inline code block, and `inline` as regular text.

**Comment by ljw1004** [comment]
It also fails to parse an indented code block inside a quoted block, for example

```
> Hello
>     Module Module1
>     End Module
> World
```

What I expect here is a CodeBlock inside the QuotedBlock. But instead it rolls the indented code block just into the same single Literal that contains the rest of the stuff.

**Comment by matthid** [comment]
Any PR which brings us closer to the spec (http://spec.commonmark.org/0.22/) is very welcome. Adding unit tests is a big plus :)

**Comment by tpetricek** [comment]
I think that our handling of indented code blocks is correct. You are always required to have a blank line around the code. The CommonMark demo requires this too: [here is a live demo](http://spec.commonmark.org/dingus/?text=%3E%20foo%0A%3E%20%20%20%20%20bar%0A%3E%20zoo%0A%0Aand%20%0A%0A%3E%20foo%0A%3E%20%60%60%60%0A%3E%20bar%0A%3E%20%60%60%60%0A%3E%20zoo).

However, we are not handling the fenced code blocks correctly. We require newlines there too. The following works:

    > Hello
    >
    > ```vb
    > Module1
    > ```
    >
    > That was an `inline` code block

... and CommonMark does not require the newlines. So, if we can fix that, that would be nice. In the meantime, adding a newline should be a reasonable workaround...

**Comment by tpetricek** [comment]
I just merged a fix for this. @matthid should I do a release so that @ljw1004 does not have to add newlines :-) or do you have some other things planned?

**Comment by matthid** [comment]
I'm a big fan of fast releases and my PR will take a while to become green :)
One note though: I disabled the update of the releases branch (with the binaries) so if you still need it you should enable it before doing the release.
