### ISSUE TITLE
Markdown with image in header generates undesired HTML tags in page title

### ISSUE THREAD

**Issue by blumu** [tpetricek/FSharp.Formatting#351]
If the header line of a markdown file contains an image, like

      # ![my logo](logo.jpg)  My title

then a `<img>` tag gets added to the title of the generated HTML page:

      <title><img src="logo.jpg" alt="my logo" />  My title </title>

instead of the desirable outcome:

     <title> My title</title>

**Comment by blumu** [comment]
I found a workaround but it's rather ugly:

    <div style="visibility: hidden; display: none;" >
    # My title
    </div>

    # ![my logo](logo.jpg)  My title

**Comment by matthid** [comment]
CommonMark spec (http://spec.commonmark.org/dingus/) creates: `<h1><img src="logo.jpg" alt="my logo" />  My title</h1>`

If we do the same I think this is correct behavior.

**Comment by tpetricek** [comment]
This is probably an issue in FsBlogLib instead - it extracts the first heading from the blog post when generating a page - and it probably does not drop the additional HTML tags that it might contain.
