### ISSUE TITLE
processDirectory should support .cshtml files

### ISSUE THREAD

**Issue by blumu** [tpetricek/FSharp.Formatting#352]
Since .md and .fsx files are already going through the razor processing pipeline it would make sense to also support raw .cshtml files in processDirectory. This can be useful when using FSharp.Formatting to generate websites and blogs.

**Comment by matthid** [comment]
I think it is easy enough to define your own `processDIrectory` with support for additional extensions (considering the code is mostly already there, for example [here](https://github.com/matthid/Yaaf.AdvancedBuilding/blob/f48f0eba8898431794887242a43ffd5d283bbb51/packages/Yaaf.AdvancedBuilding/content/generateDocsInclude.fsx#L122)). Just use `RazorEngine` like we use it [here](https://github.com/tpetricek/FSharp.Formatting/blob/master/src/Common/Razor.fs)

For blogs you probably want to use FSF as library (or at least in a script file) such that adding your own code is easy. Feel free to further explain your scenario though.
