### ISSUE TITLE
What can we do to stop the FSharp.Core hell thats experienced with F#4

### ISSUE THREAD

**Issue by 7sharp9** [tpetricek/FSharp.Formatting#356]
I cant seem to get fsformatting of project scaffold to work with F#4 seems like FSharp.Core from F#4 is causing lots of headaches especially from fsx files.  

Seems to be an issue due to FCS and FSharp.Core references interfering with scripts etc.

What can we do to stop this?
/cc @dsyme

**Comment by matthid** [comment]
You speak of https://github.com/tpetricek/FSharp.Formatting/issues/328 and that's only on macs, correct?

**Comment by 7sharp9** [comment]
Im not sure who it will effect, but yes I am using a mac
