### ISSUE TITLE
Improve exception handling in literate programming

### ISSUE THREAD

**Issue by neoeinstein** [tpetricek/FSharp.Formatting#360]
I've tried `include-value`, `include-output`, and `include-it`. None work if I throw in a `Json.parse` or `Json.tryParse` in the same evaluation block. I've even tried re-defining it in the local file and I still can't get any value other than `No value has been returned`. Any ideas where I am going wrong?
```fsharp
(** Min repro: *)
(*** hide ***)
#I @"packages\Aether\lib\net35"
#I @"packages\Chiron\lib\net45"
#r "Aether.dll"
#r "Chiron.dll"
open Chiron
(** Just Chiron parse: *)
(*** define-output:test***)
Json.parse "{}"
(*** include-it:test ***)
(** Just int parse: *)
(*** define-output:intP ***)
System.Int32.Parse "42"
(*** include-it:intP ***)
(** Both parse: *)
(*** define-output:both ***)
Json.parse "{}"
System.Int32.Parse "42"
(*** include-it:both ***)
(** Yep... *)
```
In both blocks where `Json.parse` is invoked, the include block shows `No value has been returned`.

Also of interest are these blocks:
```fsharp
Number 125m |> Json.format
```
binds correctly, but
```fsharp
"125" |> Json.parse |> Json.format
```
doesn't bind either.

**Comment by neoeinstein** [comment]
I think I just found the silent error that wasn't being propogated back to me:
```
System.TypeInitializationException: The type initializer for '<StartupCode$Chiron>.$Chiron' threw an exception. ---> System.IO.FileNotFoundException: Could not load file or assembly 'FParsec, Version=1.0.0.0, Culture=neutral, PublicKeyToken=40ccfc0a09edbb5d' or one of its dependencies. The system cannot find the file specified.
   at <StartupCode$Chiron>.$Chiron..cctor()
   --- End of inner exception stack trace ---
   at Chiron.Parsing.Json.get_parse()
   at <StartupCode$FSI_0021>.$FSI_0021.main@()
```

**Comment by neoeinstein** [comment]
Yep. This was mainly on my end. Is there a way to propagate this error back as the result for any bound value when such a binding error occurs during evaluation?

**Comment by matthid** [comment]
Was the exception logged properly? How did you find it? Where did you expect it in the first place?

**Comment by matthid** [comment]
Tracked in #370
