### ISSUE TITLE
[question] error on building docs

### ISSUE THREAD

**Issue by haf** [tpetricek/FSharp.Formatting#367]
```
FSharp.Formatting Error: 0 : Current source file 'file:///private/tmp/mono--fsharp20151201-10070-r6y3b5/src/fsharp/FSharp.Core/prim-types.fs' doesn't reside in source folder 'file:///Users/h/dev/suave/suave'
```

What does that mean? Is it good? Bad? Fish?

Anything that doesn't cause exit code <> 0 surely should not be 'error', but 'warning' at the highest?

**Comment by matthid** [comment]
This probably means that your `sourceFolder` parameter is not correct for our github-link generation (https://github.com/tpetricek/FSharp.Formatting/blob/master/src/FSharp.MetadataFormat/Main.fs#L1202).

Or it is a bug in our detection code: https://github.com/tpetricek/FSharp.Formatting/blob/master/src/FSharp.MetadataFormat/Main.fs#L202

But without further context I cannot say which case you hit (I guess the first one), but I would assume that your github links on the generated documentation generation are not working.

**Comment by matthid** [comment]
Well it is an error we can recover from by not including links to the source code (but certainly an error). Not sure if we should return exit `<>` 0 for this.
