### ISSUE TITLE
Funky operator parameters

### ISSUE THREAD

**Issue by haf** [tpetricek/FSharp.Formatting#368]
<img width="731" alt="screen shot 2015-12-19 at 10 31 37" src="https://cloud.githubusercontent.com/assets/193115/11912404/bc93fa6e-a63b-11e5-9328-da102ac5b0dc.png">

Why? Intended?

**Comment by matthid** [comment]
One part is https://github.com/tpetricek/FSharp.Formatting/issues/269 (the ugly names) the other part is that you probably didn't include the `style.css` style file or the `tips.js` file which should make sure that the signatures are tool-tips instead of direct text.

**Comment by haf** [comment]
Close in favour of #269
