### ISSUE TITLE
FSharp.Data.TypeProviders references FSharp.Core 4.4.0 but imported 4.3.1

### ISSUE THREAD

**Issue by haf** [tpetricek/FSharp.Formatting#369]
```
$  mono --debug packages/docs/FSharp.Formatting.CommandTool/tools/fsformatting.exe metadataFormat --generate --dllFiles src/Suave/bin/Release/Suave.dll --outDir docs/output/reference --layoutRoots packages/docs/FSharp.Formatting/templates/reference --parameters "page-author" "Henrik Feldt, Ademar Gonzales" "page-description" "A package for ..." "github-link" "https://github.com/suaveio/suave" "project-name" "Suave" "root" "http://suave.io/"

// snip

Compilation errors:
 - error: (0, 0) Assembly
    `FSharp.Data.TypeProviders, Version=4.4.0.0, Culture=neutral, PublicKeyToken=f536804aa0eb945b'
    references
    `FSharp.Core, Version=4.4.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
    which has a higher version number than imported assembly
    `FSharp.Core, Version=4.3.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
```

**Comment by matthid** [comment]
Sorry, I never used this tool and therefore have no plans to maintain it. That said I think a assembly redirect on fsformatting.exe for FSharp.Core 4.4.0.0 might help here ;)

**Comment by haf** [comment]
Well, you don't have to solve it then Matthias.

Didn't work with the assembly redirect. Seems that F# Formatting is not dependent on FSharp.Data.TypeProviders

**Comment by matthid** [comment]
Uah :(. I think the problem "might" be that type providers need to be loaded (to get type information), but later we use all "loaded" assemblies in RazorEngine... Since FAKE moved to F# 4 I see these things from time to time. However I'm not sure why the assemly redirect doesn't solve the issue :(

**Comment by haf** [comment]
If this is going to be used to generate docs for non 4.0 libraries then it may pose a problem. It correctly finds version 4.3.0 of F#, because that's what Suave uses which is loaded first. The problem is that you're loading stuff into your app domain without knowing how the different versions may interact. Because afterwards, 4.4.0 is needed by the doc libs, and then it can't load a different version of an already loaded assembly.

**Comment by haf** [comment]
I just want to generate docs. What should I download and what command should I run?

**Comment by haf** [comment]
Seems like the version is wrong if you're loading 4.4.0 stuff:

```
monodis --assembly packages/docs/FSharp.Formatting.CommandTool/tools/FSharp.Core.dll | grep Version
Version:       4.3.0.0
```

**Comment by matthid** [comment]
I'm now confused... Where is `FSharp.Data.TypeProviders` actually comming from, if its not from suave (https://github.com/SuaveIO/suave/blob/master/paket.lock)?

Yes FSF is acutally still build against 4.3 but references FSharp.Compiler.Service 1.4.x which might default to FSharp.Core 4.4 on some places...

To answer your `just want to generate docs` question: I think using FAKE and a build script is the most used method to use FSF:
- Download and edit https://github.com/tpetricek/FSharp.Formatting/blob/master/docs/tools/generate.fsx
- Call `FAKE.exe generate.fsx` from your "main" build script like we do here https://github.com/tpetricek/FSharp.Formatting/blob/master/build.fsx#L271

Maybe we just need to update the commandtool to F# 4 and add all assembly redirects to fix this...

**Comment by haf** [comment]
We don't reference `FSharp.Data.TypeProviders` in the file you linked...

And even if we were the tool should not crash on it. Or if it did, at least say how it got there.

I'm not going to use FAKE because this tool is broken.

Still trying to figure out where the reference comes from. It may be some docs we have that has a reference to them as a sample.

**Comment by haf** [comment]
I'm unsubscribing, found a different tool for docs. If you need me, mention me.

**Comment by matthid** [comment]
> Or if it did, at least say how it got there.

We can't because we cannot tell how or where an assembly got loaded at the point of the error (they just are loaded).

> Why don't you implement a ruby gem so I can use albacore with this tool?

Don't know any of those :)

> but there's a lot of friction going on in this tool and that's really frustrating. I've literally spent DAYS trying to make this project work.

I agree :) Most of our users (including myself) don't use the tool AFAIK, thats probably the reason why it hasn't got a lot of love lately. A lot of new features even can't be used with the tool. For example: We have an optional parameter (https://github.com/tpetricek/FSharp.Formatting/blob/master/src/FSharp.MetadataFormat/Main.fs#L1198) in place which allows you to specify which assemblies RazorEngine should use in the C# compiler call (to work around such things where weird assemblies happen to be loaded).

@haf 
> I'm unsubscribing, found a different tool for docs 

Sad to hear this :(

Actually in the mean time I released https://www.nuget.org/packages/FSharp.Formatting.CommandTool/2.12.1-alpha2 which might or might not fix the errors you are seeing (simply upgraded the tool to F# 4)
