### ISSUE TITLE
Markdown: Underscores in the middle of a word translate as emphasis

### ISSUE THREAD

**Issue by amazingant** [tpetricek/FSharp.Formatting#376]
I can't find a part of the CommonMark spec that explicitly states it rather than just being implied by the [left/right flanking delimiter][1] rules, but emphasis with the underscore like `some_words_here` should be translated as `some_words_here`, but come out of FSharp.Markdown as `some<em>words</em>here`. Spec has a [few examples of this][2]; makes snake-case value names output wrong :grimacing:

Edit: Forgot links

[1]: http://spec.commonmark.org/0.23/#left-flanking-delimiter-run
[2]: http://spec.commonmark.org/0.23/#example-326

**Comment by matthid** [comment]
The tests for the common-mark spec are already implemented so if you have some time feel free to enable them an send a PR. Would be really appreciated as I only had time to implement [two sections](https://github.com/tpetricek/FSharp.Formatting/pull/343), namely 'Fenced code blocks' and 'Indented code blocks'.

Just add 'Emphasis and strong emphasis' to [here](https://github.com/tpetricek/FSharp.Formatting/blob/master/tests/FSharp.Markdown.Tests/CommonMarkSpecTest.fs#L20) and fix the failing unit tests :)

**Comment by tpetricek** [comment]
This is one place where CommonMark makes a lot more sense than original Markdown :) would love to see this behaviour improved!

**Comment by amazingant** [comment]
I can't actually get the tests to run on my system. I'll take another look later, but so far the version of Fake in `paket.lock` thinks it needs to use mono to run MSBuild on Windows 10, and that the given NUnit expects me to have MSBuild 12 installed (I only have 14, as I've never installed VS 2013 on this system).

**Comment by matthid** [comment]
Feel free to update everything with paket update. If it doesn't help we might need to file an issue in FAKE? For the NUnit problem I'm not sure what's going on.

**Comment by amazingant** [comment]
It did look like the latest Fake was working correctly, but that was the last thing I got finished. I'm closing in on a 1.0 release on a project at work, so it might be a week or two before I have time to really dig into this.

**Comment by tpetricek** [comment]
This sounds like an instance of https://github.com/fsharp/FSharp.Compiler.Service/issues/337

@dsyme @rneatherway Is this in the 1.4.2.* branch of F.C.S. releases too?

**Comment by rneatherway** [comment]
The new project cracker is only in 2.X I'm afraid.

**Comment by tpetricek** [comment]
@rneatherway Thanks!

@dungpa @vasily-kirichenko Is the latest version of FSharpVSPowerTools.Core going to work with FCS 2.x? If so, we should be able to update the reference in F# Formatting... 

Although I guess that would only work if FAKE also did that (cc @forki)...

**Comment by vasily-kirichenko** [comment]
I didn't know there is 2.x version of FCS. We could try to update to it and run the tests.

**Comment by tpetricek** [comment]
I'm closing this in favor of #389, which does not have unrelated discussion :)
