### ISSUE TITLE
Reflection or "Method not found" Exceptions from CodeFormatAgent.fs

### ISSUE THREAD

**Issue by Thorium** [tpetricek/FSharp.Formatting#396]
I'm using ProjectScaffold template (and Windows environment). ProjectScaffold generates documentation with FSharp.Formatting.

Now, my build script is failing to FSharp.Formatting file CodeFormatAgent.fs interaction with FSharpVSPowerTools.Core:
`SourceCodeClassifier.getCategoriesAndLocations(...)` (I even tried to update the reference to new FSharpVSPowerTools version where the corresponding method is renamed to `getCategorizedSpans` but it didn't help).

The exceptions with my source file (/docs/tools/../content/index.fsx) depends on what I have inside the file, but is never working. I would be perfectly happy with this file content:

```
(*** hide ***)
// This block of code is omitted in the generated HTML documentation. Use 
// it to define helpers that you do not want to show in the documentation.
#I "../../bin"
#I @"./../../packages/Owin/lib/net40"

(**
Hello World!
======================

Documentation...

Example
-------

		[lang=cs]
		using System;
		using Owin;
		[assembly: Microsoft.Owin.OwinStartup(typeof(MyServer.MyWebStartup))]
		namespace MyServer
		{
		}

That's it.

The project is hosted on [GitHub][gh] which is nice.
  [content]: https://github.com
*)

```
The exceptions will raise:
Generating 'C:\git\Owin.Compression\docs\tools\..\content/index.html'
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.MissingMethodException: Method not found: 'Microsoft.FSharp.Collections.FSharpList`1<SynModuleDecl> SynModuleOrNamespace.get_Item3()'.
   at FSharp.CodeFormat.CodeFormatAgent.ParseSource(String file, String source, FSharpOption`1 options, FSharpOption`1 defines) in C:\git\FSharp.Formatting\src\FSharp.CodeFormat\CodeFormatAgent.fs:line 400

And:
Error: System.MissingMethodException: Method not found: 'FSharpVSPowerTools.CategorizedColumnSpan`1<!!0>[] FSharpVSPowerTools.SourceCodeClassifier.getCategoriesAndLocations(FSharpVSPowerTools.SymbolUse[], FSharpVSPowerTools.ParseAndCheckResults, FSharpVSPowerTools.LexerBase, Microsoft.FSharp.Core.FSharpFunc`2<Int32,System.String>, Microsoft.FSharp.Collections.FSharpList`1<FSharpVSPowerTools.OpenDeclaration>, Microsoft.FSharp.Core.FSharpOption`1<System.Collections.Generic.Dictionary`2<System.String,Microsoft.FSharp.Collections.FSharpList`1<System.String[]>>>)'.

And:
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.MissingMethodException: Method not found: 'Microsoft.FSharp.Collections.FSharpList`1<SynModuleDecl> SynModuleOrNamespace.get_decls()'.
   at Microsoft.FSharp.Core.Operators.Raise[T](Exception exn)
   at FSharp.CodeFormat.CodeFormatAgent.ParseSource(String file, String source, FSharpOption`1 options, FSh

**Comment by tpetricek** [comment]
We just fixed a bug in ProjectScaffold: https://github.com/fsprojects/ProjectScaffold/issues/243

Can you check that you have the latest version of everything?

**Comment by Thorium** [comment]
My versions are FSharp.Formatting.2.14.0 (from NuGet) and FSharpVSPowerTools.Core.2.3.0 (from NuGet) and I tried also the GitHub versions...

**Comment by tpetricek** [comment]
Can you try 2.14.1, released just today :) ?

**Comment by Thorium** [comment]
Seems to work, thanks!

**Comment by Thorium** [comment]
By the way, syntax highlight for C# code goes wrong on this line:
`var path = "c:\\temp\\"; //server path`
It misses `\\` and thinks the last `\"` is not break for quotation.

This is so minor thing that I don't create a new issue for that. Who uses C# anyways?

**Comment by tpetricek** [comment]
Can you open a separate issue to track this?
