### ISSUE TITLE
FSharpVSPowerTools.Core 2.3 is unlisted

### ISSUE THREAD

**Issue by forki** [tpetricek/FSharp.Formatting#401]
@vasily-kirichenko @dungpa @tpetricek 

FSharpVSPowerTools.Core 2.3 was unlisted but latest FSharp.Formatting is depending on it.
We should update FSF

**Comment by dungpa** [comment]
Why unlisted? I still see it in https://www.nuget.org/packages/FSharpVSPowerTools.Core/.

**Comment by forki** [comment]
mhm. WTF.

**Comment by forki** [comment]
Seems something strange is going on on nuget.org

**Comment by tpetricek** [comment]
Updating FSF sounds like a good idea anyway, I guess?
