### ISSUE TITLE
Single quote in function name, turns code in to red.

### ISSUE THREAD

**Issue by Thorium** [tpetricek/FSharp.Formatting#403]
This is a character: `'a'`

But this is a function:

```
let myloop() =
   let rec myloop' acc
      myloop' (acc+1)
   myloop' 0
```

Something goes wrong here:
https://logary.github.io/api/

**Comment by tpetricek** [comment]
As far as I can see, that part of documentation is not processed by F# formatting, but some (broken :-)) JavaScript code formatter.
