### ISSUE TITLE
generated HTML documents should contain a comment

### ISSUE THREAD

**Issue by smoothdeveloper** [tpetricek/FSharp.Formatting#419]
it is frequent to get PR on HTML files generated by FSharp.Formatting:

https://github.com/fsprojects/VisualFSharpPowerTools/pull/1461#issuecomment-237899706
https://github.com/hypelib/Hype/pull/7#issuecomment-233166644

It seems a disclaimer comment should be in the HTML code to mention that the file was generated from a specific matching .fsx file.

**Comment by matthid** [comment]
I think adding a disclaimer in the default templates is really enough.

**Comment by tpetricek** [comment]
+1 for modifying the ProjectScaffold's template. You can send a PR to this file:

https://github.com/fsprojects/ProjectScaffold/blob/master/docs/tools/templates/template.cshtml
