### ISSUE TITLE
Render properties of a record type

### ISSUE THREAD

**Issue by forki** [tpetricek/FSharp.Formatting#47]
Hi,

I have a record type defined like this:

![image](https://f.cloud.github.com/assets/57396/1370615/ab78282e-3a25-11e3-81d6-888fb2a3b631.png)

and it is rendered as:

![image](https://f.cloud.github.com/assets/57396/1370621/b6da8af4-3a25-11e3-86fb-a86da6551753.png)

It would be nice if the properties FSharp.Formatting would also render the properties.

Cheers,
Steffen

**Comment by matthid** [comment]
Can probably closed, see http://fsharp.github.io/FAKE/apidocs/fake-releasenoteshelper-releasenotes.html
