### ISSUE TITLE
Don't render static private members

### ISSUE THREAD

**Issue by forki** [tpetricek/FSharp.Formatting#59]
Hi,

![image](https://f.cloud.github.com/assets/57396/1435633/a9046ee2-4144-11e3-9bb1-20657719e2b8.png)

renders:

![image](https://f.cloud.github.com/assets/57396/1435635/bcaf7cb6-4144-11e3-8b72-1198e7f296bc.png)

It's private and therefor I think it should be omitted.

Cheers,
Steffen

**Comment by matthid** [comment]
I'm pretty sure we now properly filter out private stuff when `publicOnly` is set to true. Please comment if this is still not working.
