### ISSUE TITLE
fsharp.core references are missing in projects

### ISSUE THREAD

**Issue by nrolland** [tpetricek/FSharp.Formatting#71]
which means Fsharp.core will default to 4.3.1 when compiled in VS 2013, which leads tests to fail on a type initialisation "method not found InteractiveChecker.Create"

Explicit references to the specific version of FSharp.Core would pin that moving part down.

**Comment by matthid** [comment]
We have now explicit references to the F# version. Maybe we should switch to the F# NuGet package? But I think this can be closed (@nrolland feel free to comment if this is still not resolved)
